services:
  backend:
    container_name: capstone-server
    image: ghcr.io/shahbaz-athwal/capstone-backend:latest
    restart: always
    env_file:
      - .env.prod
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.capstone-api.rule=Host(`capstone-server.shahcodes.in`)"
      - "traefik.http.routers.capstone-api.entrypoints=websecure"
      - "traefik.http.routers.capstone-api.tls=true"
      - "traefik.http.routers.capstone-api.tls.certresolver=myresolver"

    networks:
      - traefik
      - db-dev

networks:
  traefik:
    external: true
  db-dev:
    external: true
