version: "3.8"

services:
  backend:
    container_name: capstone-backend
    build:
      context: .
      dockerfile: ./apps/backend/Dockerfile.prod
    restart: always
    env_file:
      - .env.prod
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.capstone-backend.rule=Host(`capstone-backend.shahcodes.in`)"
      - "traefik.http.routers.capstone-backend.entrypoints=websecure"
      - "traefik.http.routers.capstone-backend.tls=true"
      - "traefik.http.routers.capstone-backend.tls.certresolver=myresolver"
      - "traefik.http.services.capstone-backend.loadbalancer.server.port=4050"
    networks:
      - traefik
      - db-dev

networks:
  traefik:
    external: true
  db-dev:
    external: true
